### ISSUE TITLE
Per-branch site

### ISSUE THREAD

**Issue by yungyuc** [pycontw/python.tw#3]
@uranusjr , where can we get the [branch previews](https://docs.netlify.com/site-deploys/overview/#deploy-preview-controls) of netlify?

**Comment by uranusjr** [comment]
The easiest way is to view on Netlify’s asmin panel, but collaboration is $15 per seat. I’ll see if I can add a deploy hook to publish the link somewhere else (e.g. email)

**Comment by uranusjr** [comment]
It seems like I can set email notifications on site deployment (including both previews and production), but the URL (http://deploy-preview-1--pythontw.netlify.com) does not seem permanent (compared to the one in admin (https://5e390f12189996ec67a0c8e7--pythontw.netlify.com/).

Send me you email if you want to try out email notifications, and I’ll add it to the notify list. We can explore alternatives (e.g. create a shared account) if that doesn’t work out.

cc @tai271828

**Comment by yungyuc** [comment]
Can the preview URL be included in CI results?

**Comment by uranusjr** [comment]
No, deploy is not done during CI. Netlify pulls source code and builds on its own.

**Comment by yungyuc** [comment]
Then, how about setting up a mailing list (searchable), or slack channel, for the preview notification?

**Comment by uranusjr** [comment]
Sounds good to me. Just send me the preferred endpoint and I’ll do the required Netlify config.

**Comment by yungyuc** [comment]
https://groups.google.com/forum/#!forum/python-tw-site-notification is created.  @uranusjr and @tai271828 are invited as members.  I set it to be public viewable, member writable, and join by invitation.

Once you join the group, ping me to elevate your permission.

**Comment by uranusjr** [comment]
Joined. Netlify seems to publish deploy notifications with `team@netlify.com`.

**Comment by yungyuc** [comment]
Google group doesn't allow adding `team@netlify.com` to member, claiming it's a 'group address'.  I lift the posting permission instead.

Let's observe for a few pushes.  If it works, close this issue.

**Comment by yungyuc** [comment]
The preview name looks predictable: https://develop--pythontw.netlify.com
