### ISSUE TITLE
www.python.tw should redirect to python.tw

### ISSUE THREAD

**Issue by yungyuc** [pycontw/python.tw#5]
Both https:// and http://www.python.tw should redirect to python.tw.

Alternately, they can be serving with the same contents.

cc @uranusjr

**Comment by uranusjr** [comment]
This should probably best set in DNS, something like

```
www.python.tw.       0       IN      CNAME   python.tw.
```

**Comment by tai271828** [comment]
I am trying an configuration similar to the above[1]. Let's see how it works later.

[1] `www 300 IN CNAME python.tw.`

**Comment by uranusjr** [comment]
Seems to work for me now.

Edit: Looks like there’s some kind of certificate problem

```
$ curl -v https://www.python.tw
* Rebuilt URL to: https://www.python.tw/
*   Trying 104.248.63.248...
* TCP_NODELAY set
*   Trying 2604:a880:400:d1::895:1...
* TCP_NODELAY set
* Immediate connect fail for 2604:a880:400:d1::895:1: Network is unreachable
* Connected to www.python.tw (104.248.63.248) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=ca; L=San Francisco; O=Netlify, Inc; CN=*.netlify.com
*  start date: Jul  3 00:00:00 2019 GMT
*  expire date: Jul  7 12:00:00 2020 GMT
*  subjectAltName does not match www.python.tw
* SSL: no alternative certificate subject name matches target host name 'www.python.tw'
* stopped the pause stream!
* Closing connection 0
* TLSv1.3 (OUT), TLS Unknown, Unknown (21):
* TLSv1.3 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.python.tw'
```

I’ll look into this later…

**Comment by yungyuc** [comment]
There was a certificate problem when I tested 30 minutes ago.  But now I tested it in private-mode safari and both http:// and https://www.python.tw redirects to https://python.tw .  I think netlify did some magic, but not sure about it.

I am closing this issue.

**Comment by uranusjr** [comment]
Yup, seems fixed now. Netlify provisions the SSL certificate based on the DNS record (previous it only contained `python.tw` so the old certificate did not contain `www.python.tw`). I guess it just needed some time to detect the DNS change.

**Comment by tai271828** [comment]
Neat!! I Thanks for the feedback!! The DNS propagation time is so unpredictable for me, so every time I can't make sure if I was doing the right configuration when applying new settings.

**Comment by uranusjr** [comment]
DNS propagation is unpredictable by design (being decentralised), unfortunately. You are definitely not alone to feel it difficult to deal with.
