### ISSUE TITLE
How to create a merge request form develop to master?

### ISSUE THREAD

**Issue by yungyuc** [pycontw/python.tw#9]
As shown in the below picture, since `develop` is the default branch, there is not a button to create merge request from `develop` to `master`.

<img width="1013" alt="Screen Shot 2020-02-07 at 07 48 30" src="https://user-images.githubusercontent.com/399122/73988656-4b85fa80-497e-11ea-830f-8f8473324b59.png">

What will be the work flow recommended to do the `develop` to `master` merge?

**Comment by uranusjr** [comment]
I can create a PR in Pull requests -> New -> configure as [master] <- [develop]

**Comment by uranusjr** [comment]
![C21DC3F3-3876-4C5A-A68E-09EB908B20A0](https://user-images.githubusercontent.com/605277/73998690-64ea6f00-499d-11ea-8fe9-5aae8c254319.jpeg)

**Comment by yungyuc** [comment]
That works for me.  cc @tai271828

**Comment by tai271828** [comment]
Ack, thanks.
